MeetingApp/Models/Repository.cs
using Microsoft.AspNetCore.Components;

namespace MeetingApp.Models
{
    public class Repository()
    {
        private static List<UserInfo> _users = new List<UserInfo>();
        private static string Location { get; set; }
        private static int NumberOfMeetings = _users.Count;
        private static string StartDate = DateTime.Now.ToShortDateString();

        public static List<UserInfo> Users
        {
         get { return _users; }   
        }

        public static void AddUser(UserInfo user)
        {
            user.Id = Users.Count + 1;
            _users.Add(user);
        }
        
        static Repository()
        {
            Location = "NewYork";
            StartDate = DateTime.Now.ToShortDateString();
            _users.Add(new UserInfo(){Id = 1, Name = "Ali", Email = "ali@gmail.com", Phone = "123456", WillAttend = true});
            _users.Add(new UserInfo(){Id = 2, Name = "Ahmet", Email = "ahmet@gmail.com", Phone = "123456", WillAttend = true});
            _users.Add(new UserInfo(){Id = 3, Name = "Canan", Email = "canan@gmail.com", Phone = "123456", WillAttend = false});
            _users.Add(new UserInfo(){Id = 4, Name = "Eyup", Email = "eyup@gmail.com", Phone = "123456", WillAttend = true});
            NumberOfMeetings = Users.Count;
        }

        public static UserInfo? GetById(int id)
        {
            return _users.FirstOrDefault(x => x.Id == id);
        }

        public static string getLocation()
        {
            return Location;
        }

        public static int getNumberOfMeetings()
        {
            return NumberOfMeetings;
        }

        public static string getStartDate()
        {
            return StartDate;
        }
    }
}

MeetingApp/Models/UserInfo.cs
using System.ComponentModel.DataAnnotations;

namespace MeetingApp.Models
{
    public class UserInfo()
    {
        public int Id { get; set; }
        
        [Required]
        public string? Name { get; set; }
        
        [Required]
        public string? Phone { get; set; }
        
        [Required]
        [EmailAddress]
        public string? Email { get; set; }
        
        [Required]
        public bool WillAttend { get; set; }
    }
}

MeetingApp/Controllers/HomeController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers
{
    public class HomeController : Controller
    {
        // GET
        public IActionResult Index(Repository repository)
        {
            return View(model: repository);
        }
    }    
}

MeetingApp/Controllers/MeetingController.cs
using Microsoft.AspNetCore.Mvc;
using MeetingApp.Models;

namespace MeetingApp.Controllers;

public class MeetingController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Apply()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Apply(UserInfo model)
    {
        if (ModelState.IsValid)
        {
            Repository.AddUser(model);
            ViewBag.AttendeCount = Repository.Users.Where(i => i.WillAttend == true).Count();
            return View("Thanks", model);
        }
        return View(model);
    }

    public IActionResult List()
    {
        return View(Repository.Users);
    }

    public IActionResult Details(int id)
    {
        return View(Repository.GetById(id));
    }
}

MeetingApp/Views/Home/index.cshtml
@model Repository
@{
    ViewBag.Title = "Homepage";
    Layout = "_LayoutHomePage";
}

<main class="text-center">
    
<h1 class="h4">Hello 👋</h1>
<p>Please indicate your Meeting Participant status</p>

<div class="card my-2">
    <ul class="list-group list-group-flush">
        <li class="list-group-item">Location: @Repository.getLocation() </li>
        <li class="list-group-item">Start Time: @Repository.getStartDate()</li>
        <li class="list-group-item">@Repository.getNumberOfMeetings() Attendees</li>
    </ul>
</div>

<a asp-controller="Meeting" asp-action="Apply" class="btn btn-sm btn-outline-primary">Apply now</a>
</main>

MeetingApp/Views/Meeting/Apply.cshtml
@model UserInfo
@{
ViewBag.Title = "Apply";
}


<h1 class="h4 text-center">Meeting Participation Form</h1>
<form action="" method="post" novalidate>
    <div asp-validation-summary="All"></div>
    <div class="mb-3">
        <label asp-for="Name" class="form-label">Name</label>
        <input asp-for="Name" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Phone" class="form-label">Phone</label>
        <input asp-for="Phone" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label">E-Mail</label>
        <input asp-for="Email" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="WillAttend" class="form-label">Meeting Attendance Status</label>
        <select asp-for="WillAttend" class="form-select">
            <option value="true">Yes, I will attend</option>
            <option value="false">No, I wont attend</option>
        </select>
    </div>
    <button class="btn btn-primary" type="submit">Send</button>
</form>

MeetingApp/Views/Meeting/Details.cshtml
@using System.Net.Mime
@model UserInfo
@{
    ViewBag.Title = "Details";
    var className = @Model.WillAttend == true ? "success" : "danger";
}

<main class="text-center">
    <h1 class="h4">Details</h1>
    <hr>
    <br>

    <p>
        <span class="alert alert-@className">
            @if (Model.WillAttend == true)
            {
                <text>Attending</text>
            }
            else
            {
                <text > Not Attending </text>
            }

        </span>
    </p>
    <br>

    <p>Name: @Model.Name</p>
    <p>Email: @Model.Email</p>
    <p>Phone: @Model.Phone</p>
    <a asp-controller="Meeting" asp-action="List " class="btn btn-outline-@className">AttendeeList</a>
</main>

MeetingApp/Views/Meeting/List.cshtml
@model List<UserInfo>
@{
 ViewBag.Title = "Participant List";
}

<main class="text-center">
    
<h1 class="h4">Meeting Participant List</h1>
<table class="table table-border">
    <thead>
    <tr>
        <td>Name</td>
        <td>Status</td>
        <td>Details</td>
    </tr>
    </thead>
    <tbody>
    @{ int i = 0; }
    @foreach (var user in Model)
    {
        if (user.WillAttend == true)
            i++;
        
        var status = user.WillAttend == true ? "Attending" : "Not Attending";
        var classname = user.WillAttend == true ? "table-success" : "table-danger";

        <tr class="@classname">
            <td>@user.Name</td>
            <td>@status</td>
            <td>
                <a href="/meeting/details/@user.Id" class="btn btn-sm btn-primary">Details</a>
            </td>
        </tr>
    }

    </tbody>
</table>
<div class="card">
    <div class="card-body">
        <span>@i people attending</span>
    </div>
</div>

</main>

MeetingApp/Views/Meeting/Thanks.cshtml
@model UserInfo
@{
    ViewBag.Title = "Summary";
}

<main class="text-center">
    <h1 class="h4">Submitted</h1>
    
    @if (Model.WillAttend == true)
    {
        <p>Thanks, @Model.Name</p>
        <p>there are @ViewBag.AttendeCount participants with you</p>
        <a href="/Meeting/List" class="btn btn-sm btn-outline-primary">Show List</a>    
    }
    else
    {
        <p >@Model.Name, we are sorry that you will not be able to attend the meeting.</p>
        <a href="/" class="btn btn-sm btn-outline-primary">HomePage</a>    

    }
    
</main>

MeetingApp/Views/Meeting/index.cshtml
@{
ViewBag.Title = "Summary";
}

<main class="text-center">
<h1 class="h4">Meeting Summary</h1>
<p>there are 20 participants with you</p>
<a href="/Meeting/List" class="btn btn-sm btn-outline-primary">Show List</a>
</main>

MeetingApp/Views/Shared/_Layout.cshtml
<!doctype html>
    <html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css" />
    <title>@ViewBag.Title - MeetingApp</title>
</head>
<body>
<div class="bg-primary text-white p-2 text-center" href="/">
    MeetingApp
</div>
<div class="container mt-3">    
    <div class="row">
        <div class="col-lg-6 mx-auto">
            <div class="card">
                <div class="card-body">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
</div>


</body>
</html>

MeetingApp/Views/Shared/_LayoutHomePage.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css"/>
    <title>@ViewBag.Title - MeetingApp</title>
</head>
<body>
<div class="bg-danger text-white p-2 text-center">
    MeetingApp
</div>
<div class="container mt-3">
    <div class="row">
        <div class="col-lg-6 mx-auto text-center" href="/">
            <div class="card">
                <div class="card-body">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
</div>


</body>
</html>